# Copyright (C) 2024 Alcides Goldoni Junior <goldoni@versatushpc.com.br>
---
- name: Ansible playbook - Install zabbix proxy (7)
  hosts: all
  become: yes
  become_method: su

  tasks:
  - name: Stop Zabbix Agent
    service: name=zabbix-agent state=restarted

  - name: Stop Zabbix Proxy
    service: name=zabbix-proxy state=restarted
    
  - name: Installation from DNF
    ansible.builtin.dnf:
      name: 
        - zabbix-release
      state: absent

  - name: Ansible zabbix proxy installation
    ansible.builtin.yum:
      name: https://repo.zabbix.com/zabbix/6.5/rhel/9/x86_64/zabbix-release-6.5-1.el9.noarch.rpm
      state: present

  - name: Installation from DNF
    ansible.builtin.dnf:
      name: 
        - zabbix-proxy-sqlite3
        - zabbix-selinux-policy
        - zabbix-sql-scripts
        - zabbix-agent
      state: present
  
  - name: Removing old databse
    command: mv /var/lib/zabbix/zabbix_proxy.db /tmp/

  - name: Zabbix configuration (saving original file)
    command: cp  /etc/zabbix/zabbix_proxy.conf  /etc/zabbix/zabbix_proxy.conf_save 

  - lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      state: present
      regexp: '^DBHost'
      line: 'DBHost=localhost'

  - lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      state: present
      regexp: '^DBName'
      line: 'DBName=zabbix'

  - lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      state: present
      regexp: '^DBUser'
      line: 'DBUser=zabbix'

  - lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      state: present
      regexp: '^DBPassword'
      line: 'DBPassword='

  - name: Add a line to a file if the file does not exist, without passing regexp
    blockinfile:
      path: /etc/zabbix/zabbix_policy.te
      block: |
        module zabbix_policy 1.2;
        require {
        type zabbix_t;
        type zabbix_port_t;
        type zabbix_var_run_t;
        class tcp_socket name_connect;
        class sock_file { create unlink };
        class unix_stream_socket connectto;
        }
        \#============= zabbix_t ==============
        allow zabbix_t self:unix_stream_socket connectto;
        allow zabbix_t zabbix_port_t:tcp_socket name_connect;
        allow zabbix_t zabbix_var_run_t:sock_file create;
        allow zabbix_t zabbix_var_run_t:sock_file unlink;

  - name: Create SELinux Policy zabbix_policy.mod and zabbix_policy.te
    command: checkmodule -M -m -o zabbix_policy.mod zabbix_policy.te

  - name: Create SELinux Policy zabbix_policy.pp and zabbix_policy.mod
    command: semodule_package -o zabbix_policy.pp -m zabbix_policy.mod

  - name: Create SELinux Policy zabbix_policy.pp
    command: semodule -i zabbix_policy.pp

  - name: Enable service zabbix agent
    ansible.builtin.service:
      name: zabbix-agent
      enabled: yes

  - name: Enable service zabbix proxy
    ansible.builtin.service:
      name: zabbix-proxy
      enabled: yes

  - name: Restart Zabbix agent
    service: name=zabbix-agent state=restarted

  - name: Restart Zabbix Proxy
    service: name=zabbix-proxy state=restarted
