# Copyright (C) 2024 Alcides Goldoni Junior <goldoni@versatushpc.com.br>
---
- name: Ansible playbook - Install zabbix agent (7)
  hosts: all
  become: yes
  become_method: su

  tasks:
  - name: Ansible zabbix agent2 installation
    ansible.builtin.yum:
      name: https://repo.zabbix.com/zabbix/6.5/rhel/9/x86_64/zabbix-release-6.5-1.el9.noarch.rpm
      state: present

  - name: Installation from DNF
    ansible.builtin.dnf:
      name: zabbix-agent2
      state: present
  
  - name: Zabbix configuration (saving original file)
    command: cp /etc/zabbix/zabbix_agent2.conf /etc/zabbix/zabbix_agent2.conf_save
  
  - lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      state: present
      regexp: '^Server=127.0.0.1'
      line: 'Server=suporte.versatushpc.com.br'

  - lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      state: present
      regexp: '^ServerActive=127.0.0.1'
      line: 'Server=suporte.versatushpc.com.br'

  - name: Enable service zabbix agent
    ansible.builtin.service:
      name: zabbix-agent2
      enabled: yes

  - name: Restart Zabbix agent
    service: name=zabbix-agent2 state=restarted

